Switch to new cheeseshop for v2 versions (#235)
This change switches to using the new v2 cheeseshop at
https://wheels.pantsbuild.org/simple/ to support future, current, and
past versions of Pants (especially those which may not be on PyPI).

I also trimmed all v2 versions from the embedded tag map, as it's no
longer necessary.

# Testing

Using `version = "2.15.0.dev4"` in my `pants.toml`

## Before:

```console
josh@cephandrius:~/work/techlabs$ pants --no-verify-config version
Bootstrapping Pants 2.15.0.dev4 using cpython 3.9.16
Installing pantsbuild.pants==2.15.0.dev4 into a virtual environment at /home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/bindings/venvs/2.15.0.dev4
ERROR: Could not find a version that satisfies the requirement pantsbuild.pants==2.15.0.dev4 (from versions: 0.0.17, 0.0.18, 0.0.20, 0.0.21, 0.0.22, 0.0.23, 0.0.24, 0.0.25, 0.0.26, 0.0.27, 0.0.28, 0.0.29, 0.0.30, 0.0.31, 0.0.32, 0.0.33, 0.0.34, 0.0.35, 0.0.36, 0.0.37, 0.0.38, 0.0.39, 0.0.40, 0.0.41, 0.0.42, 0.0.43, 0.0.44, 0.0.45, 0.0.46, 0.0.47, 0.0.48, 0.0.49, 0.0.50, 0.0.51, 0.0.52, 0.0.53, 0.0.54, 0.0.55, 0.0.56, 0.0.57, 0.0.58, 0.0.59, 0.0.60, 0.0.61, 0.0.62, 0.0.63, 0.0.64, 0.0.65, 0.0.66, 0.0.67, 0.0.68, 0.0.69, 0.0.70, 0.0.71, 0.0.72, 0.0.73, 0.0.74, 0.0.75, 0.0.76, 0.0.77, 0.0.79, 0.0.80, 0.0.81, 0.0.82, 1.0.0, 1.0.1, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.15.0, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.20.0, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.26.0, 1.27.0, 1.28.0, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.7.0rc0, 2.7.0rc1, 2.7.0rc2, 2.7.0rc3, 2.7.0rc4, 2.7.0rc5, 2.7.0, 2.7.1rc0, 2.7.1rc1, 2.7.1, 2.7.2rc0, 2.7.2rc1, 2.7.2rc2, 2.7.2, 2.8.0rc0, 2.8.0rc1, 2.8.0rc2, 2.8.0rc3, 2.8.0rc4, 2.8.0rc5, 2.8.0rc6, 2.8.0, 2.8.1rc0, 2.8.1rc1, 2.8.1rc2, 2.8.1, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0rc3, 2.9.0rc4, 2.9.0rc5, 2.9.0rc6, 2.9.0, 2.9.1rc0, 2.9.1rc1, 2.9.1rc2, 2.9.1, 2.9.2rc0, 2.9.2, 2.10.0rc0, 2.10.0rc1, 2.10.0rc2, 2.10.0rc3, 2.10.0rc4, 2.10.0rc5, 2.10.0, 2.10.1rc0, 2.10.1rc1, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0rc3, 2.11.0rc4, 2.11.0rc5, 2.11.0rc6, 2.11.0, 2.11.1rc0, 2.11.1rc1, 2.11.1rc2, 2.11.1rc3, 2.11.1, 2.12.0a0, 2.12.0rc0, 2.12.0rc1, 2.12.0rc2, 2.12.0rc3, 2.12.0, 2.12.1rc0, 2.12.1rc1, 2.12.1rc2, 2.12.1rc3, 2.12.1rc4, 2.12.1, 2.13.0a0, 2.13.0a1, 2.13.0rc0, 2.13.0rc1, 2.13.0rc2, 2.13.0rc3, 2.13.0, 2.13.1rc0, 2.13.1rc1, 2.13.1rc2, 2.13.1, 2.14.0a0, 2.14.0a1, 2.14.0rc0, 2.14.0rc1, 2.14.0rc2, 2.14.0rc3, 2.14.0rc4, 2.14.0rc5, 2.14.0, 2.14.1rc0, 2.14.1, 2.14.2rc0, 2.14.2rc1, 2.14.2rc2, 2.14.2, 2.15.0a0, 2.15.0a1, 2.15.0rc0, 2.15.0rc1, 2.15.0rc2, 2.15.0rc3, 2.15.0rc4, 2.15.0rc5, 2.15.0rc6, 2.15.0rc7, 2.15.0, 2.15.1rc0, 2.15.1rc1, 2.15.1rc2, 2.15.1rc3, 2.15.1, 2.15.2rc0, 2.15.2, 2.16.0.dev6, 2.16.0.dev7, 2.16.0a0, 2.16.0a1, 2.16.0rc0, 2.16.0rc1, 2.16.0rc2, 2.16.0rc3, 2.16.0rc4, 2.16.0rc5, 2.16.0rc6, 2.16.0rc7, 2.16.0, 2.16.1rc0, 2.17.0.dev0, 2.17.0.dev1, 2.17.0.dev2, 2.17.0.dev3, 2.17.0.dev4, 2.17.0.dev5, 2.17.0a1, 2.17.0rc0, 2.17.0rc1, 2.17.0rc2, 2.18.0.dev0, 2.18.0.dev1, 2.18.0.dev3, 2.18.0.dev4, 2.18.0.dev5, 2.18.0.dev6)
ERROR: No matching distribution found for pantsbuild.pants==2.15.0.dev4
Install failed: Command '['/home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/bindings/venvs/2.15.0.dev4/bin/python', '-sE', '-m', 'pip', '--disable-pip-version-check', '--no-python-version-warning', '--log', PosixPath('/home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/bindings/venvs/2.15.0.dev4/pants-install.log'), 'install', '--quiet', '--find-links', 'file:///home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/bindings/find_links/2.15.0.dev4/458c7f04/index.html', '--progress-bar', 'off', 'pantsbuild.pants==2.15.0.dev4']' returned non-zero exit status 1.
More information can be found in the log at: /home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/bindings/logs/install.log

Error: Isolates your Pants from the elements.

Please select from the following boot commands:

scie-pants
bootstrap-tools
pants
pants-debug
update

You can select a boot command by passing it as the 1st argument or else by setting the SCIE_BOOT environment variable.

ERROR: Failed to establish atomic directory /home/josh/.cache/nce/c55ee58a557d20bd4b109870e5a01b264c0d501ce817cce29502b2552903834d/locks/install-13b76a5f221fbf00f926015801135b36cf314552b34ae51c4f99ef69e8955618. Population of work directory failed: Boot binding command failed: exit status: 1
```

## After

```console
josh@cephandrius:~/work/techlabs$ /home/josh/work/scie-pants/dist/scie-pants-linux-x86_64 --no-verify-config version
Bootstrapping Pants 2.15.0.dev4 using cpython 3.9.16
Installing pantsbuild.pants==2.15.0.dev4 into a virtual environment at /home/josh/.cache/nce/86678ba5eb342c01c45cd430039275d57aa947481b8a2f75c85fbade58ea5581/bindings/venvs/2.15.0.dev4
New virtual environment successfully created at /home/josh/.cache/nce/86678ba5eb342c01c45cd430039275d57aa947481b8a2f75c85fbade58ea5581/bindings/venvs/2.15.0.dev4.
20:58:02.44 [INFO] Initializing scheduler...
20:58:02.52 [INFO] Scheduler initialized.
2.15.0.dev4
```