Update jump & science to improve error message for bad SCIE_BOOT (#284)
This updates to jump to 0.13.0, which improves the error message for a
bad `SCIE_BOOT` value. For example `SCIE_BOOT='update pants' pants` from
https://pantsbuild.slack.com/archives/C046T6T9U/p1695047533069949 now
shows:

```
Error: `SCIE_BOOT=update pants` was found in the environment but "update pants" does not correspond to any scie-pants commands.

Isolates your Pants from the elements.

Please select from the following boot commands:

<default> (when SCIE_BOOT is not set in the environment)  Detects the current Pants installation and launches it.
bootstrap-tools                                           Introspection tools for the Pants bootstrap process.
update                                                    Update scie-pants.

You can select a boot command by setting the SCIE_BOOT environment variable.
```

This also requires updating science to 0.2.1, for the `descriptions` to
be propagated appropriately.